### PR TITLE
Testimonials section

### PR DESCRIPTION
**Pull request by jasonappah**
Merged in the footer branch to make building this less annoying so it'll be easier to review + merge #8 first :)

### CODE REVIEW

**Review by ZzRanger — COMMENTED** [review]
This looks great! Just a few things I noticed:

1. Based on the Figma the footer seems to have a 2 column format on mobile, and the "back to top arrow" is on the same row as the "Nebula Labs" logo.

Current:
Screenshot 2023-09-03 at 11 34 01 PM

Figma:


2. The "Next" button on the carousel doesn't seem to be working on my browser?

**Comment by ZzRanger** [comment]
Oh noticed 1 more thing: image sizes on testimonials are a bit inconsistent
Screenshot 2023-09-03 at 11 46 31 PM
Screenshot 2023-09-03 at 11 46 34 PM
Screenshot 2023-09-03 at 11 46 37 PM

**Comment by jasonappah** [comment]
Looks like the broken next button and inconsistent image sizes are only in Firefox 💀 

I've tested in Safari and Chrome and didn't see that behavior so will need to debug this later

**Comment by jasonappah** [comment]
Created NW-10 to handle fixing the image sizing at some point in the future

**Pull request merged**
