### PR TITLE
Safari improvements

### PR DESCRIPTION
**Pull request by TyHil**
On the main page, the `Header`, `Projects`, and `CTA` all seem to cause webkit lag.

- In the header it seems like it's `useBlobBg.tsx` causing problems. Not sure why.

- I may have fixed the projects. Apparently it's better to animate `translate` instead of `background-position`. It needs testing on an actual mac tho. The animation might be too fast and there may be a line showing up between the two images animating.

- In the CTA the `Blob` elements seem to be causing lag but they're not animating so idk why. Maybe also the radial gradients. Or maybe it's just my webkit emulator.

In testing each of these it's probably best to remove the other two from the `index.tsx` file.

### CODE REVIEW

**Comment by TyHil** [comment]
@jasonappah and @Jake3231 would y'all test this and maybe put a little work into it. I was just going around removing things until it stopped lagging, getting more and more specific, maybe y'all can do the same.

**Comment by Shaurya0108** [comment]
> @jasonappah and @Jake3231 would y'all test this and maybe put a little work into it. I was just going around removing things until it stopped lagging, getting more and more specific, maybe y'all can do the same.

Im going to try it out

**Comment by Jake3231** [comment]
I can take a look at this too

**Comment by Jake3231** [comment]
So far much improved, but not 100% there.

**Comment by Jake3231** [comment]
From what I see on Safari 17.3 on macOS 14.3:

- Much better perf on this branch
- The background at the top of the page no longer animates
- The stars animation behind "check out our projects" does have a visible line.
- The whole "check out our projects" section appears very pixelated
Screenshot 2024-02-06 at 4 23 09 PM

**Comment by TyHil** [comment]
An easier but less cool solution could be to conditionally apply some JS/CSS that disables the background animations on Safari.

This could be done by accessing the userAgent string.

What do y'all think?

**Comment by jasonappah** [comment]
I had typed out a comment on this pr a couple days ago but apparently didn't hit send here 😔 

I'm good with disabling the hero animation on Safari until we can figure out a better solution. Not too sure what other options would be good to explore here tbh. The stars animation wasn't planned/in Figma, it was just a nice to have that I added. If we also need to disable it/remove it all together, that's also fine

**Comment by Jake3231** [comment]
> An easier but less cool solution could be to conditionally apply some JS/CSS that disables the background animations on Safari.
> 
> This could be done by accessing the userAgent string.
> 
> What do y'all think?

I agree with @jasonappah that disabling the hero animation for Safari is a fine solution for now to keep the project moving forward on all platforms. Might be a nice low priority fix later. Just something to watch out for, I think iPad reports its user agent as desktop OS X , and iPhone is reporting as iOS. Only actual macOS Safari is having the issue.

**Comment by Shaurya0108** [comment]
Last time I worked on it the main issue was with using the Blob file and components for animations. They slowed down the performance.

**Comment by Jake3231** [comment]
@nl32 and I tested on Safari on macOS, this is significantly better now.

**Comment by TyHil** [comment]
I think this should be ready then!

**Comment by Jake3231** [comment]
Tested again on Safari 17.4.1 and it's a bit improved on old and patched versions, but it's still much better on this branch. Apple made some big Safari perf/compatibility fixes over the course of macOS 14's release cycle, and it seems that this is getting some benefit.

**Review by RubenOlano — APPROVED** [review]
Runs great :)

**Pull request merged**
